[build]
builder = "NIXPACKS"

[deploy]
startCommand = "gunicorn pochita_project.wsgi --log-file -"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[deploy.preDeploy]
commands = [
  "python manage.py migrate --noinput",
  "python manage.py collectstatic --noinput"
]

